### ISSUE TITLE
Unable to use ULID in ModelBinding for Asp.net (core) 

### ISSUE THREAD

**Issue by akrock** [Cysharp/Ulid#13]
Attempting to use a ULID as a route parameter in a Asp.net core application will currently fail due to the following exception.

```
System.InvalidOperationException: Could not create an instance of type 'System.Ulid'. Model bound complex types must not be abstract or value types and must have a parameterless constructor. Alternatively, give the 'input' parameter a non-null default value.
```

Example code: 
```
using System;
using Microsoft.AspNetCore.Mvc;

namespace WebAppBinding
{
    [Route("test")]
    [ApiController]
    public class TestController : ControllerBase
    {

        [Route("{input}")]
        [HttpGet]
        public Ulid Echo([FromRoute] Ulid input)
        {
            return input;
        }
    }
}
```

Expected Result:
Much like a GUID a ULID is a valid route parameter.

Current Result:
The documented exception above.

This issue can be prevented by adding a `TypeConverter` for ULID that is able to convert from a string value. I will open a PR with working changes shortly.

**Comment by neuecc** [comment]
I've released 1.1.0, it includes this fix.
Thanks!

**Comment by SuhutDev** [comment]
> Attempting to use a ULID as a route parameter in a Asp.net core application will currently fail due to the following exception.
> 
> ```
> System.InvalidOperationException: Could not create an instance of type 'System.Ulid'. Model bound complex types must not be abstract or value types and must have a parameterless constructor. Alternatively, give the 'input' parameter a non-null default value.
> ```
> 
> Example code:
> 
> ```
> using System;
> using Microsoft.AspNetCore.Mvc;
> 
> namespace WebAppBinding
> {
>     [Route("test")]
>     [ApiController]
>     public class TestController : ControllerBase
>     {
> 
>         [Route("{input}")]
>         [HttpGet]
>         public Ulid Echo([FromRoute] Ulid input)
>         {
>             return input;
>         }
>     }
> }
> ```
> 
> Expected Result: Much like a GUID a ULID is a valid route parameter.
> 
> Current Result: The documented exception above.
> 
> This issue can be prevented by adding a `TypeConverter` for ULID that is able to convert from a string value. I will open a PR with working changes shortly.

hi you have complete sample with asp.net, i am stuck on this.. thx

**Comment by DoomerDGR8** [comment]
I need help with this as well.
