### ISSUE TITLE
Library Collision with Unity Collections Package

### ISSUE THREAD

**Issue by virtushda** [Cysharp/Ulid#33]
Not sure if you can do anything about this, but Unity's native collection library also has an unsafe.dll which stops unity in it's tracks.
![image](https://user-images.githubusercontent.com/14203100/129433989-1a5b4505-c021-489f-bc94-4a317abd7900.png)

**Comment by virtushda** [comment]
For anyone else: It looks like deleting the library provided with this package fixes the issue. Not the most stable solution though...

**Comment by neuecc** [comment]
guide:
https://github.com/Cysharp/ZString/#unity

0.11.0 details:
https://forum.unity.com/threads/please-update-com-unity-collections-reference-of-system-runtime-compilerservices-unsafe.732056/#post-5972735
