### ISSUE TITLE
ID Collisions When Generated from Strings

### ISSUE THREAD

**Issue by virtushda** [Cysharp/Ulid#34]
We're using Ulid to generate unique IDs based on names.
For the most part it works, but we're seeing a lot of ID collisions in certain circumstances...

For instance, these two collide:
![image](https://user-images.githubusercontent.com/14203100/130688872-c86ef193-9d34-43a4-ae1b-f648d0e6c558.png)
![image](https://user-images.githubusercontent.com/14203100/130689116-70cfeef1-9033-40cf-a48f-0e2d22cde9b6.png)

I'm sorry if I'm misunderstanding how this works, but I was under the impression that Ulids generated should be more unique than this?

This is the implementation: (Sorry, code tags butchered everything..)
![image](https://user-images.githubusercontent.com/14203100/130690352-d5845926-5d7e-466c-ba1c-194bde9c4263.png)

.ToUlid:
![image](https://user-images.githubusercontent.com/14203100/130690317-21723d55-aacd-494e-8a5d-658cffd17c31.png)

**Comment by neuecc** [comment]
Ulid representation is [Time + Randomness].
andalso, Parse expects ulid's string representation.
Isn't it wrong to express name as Ulid?

**Comment by virtushda** [comment]
I guess I misunderstood what this system is meant to do!
