### ISSUE TITLE
Code modernisation

### ISSUE THREAD

**Issue by TimothyMakkison** [Cysharp/Ulid#38]
Optimize and modernise code to be in parity with [System.Guid](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Guid.cs)

### Modernisation
- Implement `ISpanFormattable`, `IComparable`, `ISpanParsable<Ulid>`, see #35 
- Remove unsafe/pinning code in favor of `ref Unsafe` see [Guid.GetHashCode](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Guid.cs#L864)
- Add if BigEndian logic (Does this library supports big endian?)

### Optimisation
- Use string.Create where possible
- Vectorize the `ToGuid`, `public Ulid(Guid guid)` shuffle.
- Vectorize equality #37 
- Vectorize Comparison see [Guid.FastCompareTo](https://github.com/dotnet/runtime/issues/53981)
- Consider vectorizing `TryWriteStringify`
- Vectorize  `internal Ulid(long timestampMilliseconds` timestamp shuffling
- Vectorize `internal Ulid(ReadOnlySpan<char> base32)`
- Vectorize `public DateTimeOffset Time`

**Comment by neuecc** [comment]
sorry for the delayed response, PR will check in next month.

**Comment by hadashiA** [comment]
#39 merged.  Thanks!
