### ISSUE TITLE
Ordering of Ulids produced at the same time

### ISSUE THREAD

**Issue by rcollina** [Cysharp/Ulid#43]
Hello,
First, I’d like to thank you for your valuable open source contributions to the .NET community.

From a cursory code analysis there seem to be no guarantees regarding ordering when the timestamp component is the same - I am however unsure about this assessment, and I could use some help.

If that’s the case, are there any plans to include additional out of the box guarantees ordering-wise?

**Comment by hadashiA** [comment]
Hello, 
As you mentioned, [ulid spec](https://github.com/ulid/spec) has a definition of monotonicity.
This guarantees sort order even if the timestamps is same.
However, we do not plan to implement this.

This is because monotonicity mode is only an ordering guarantee on one machine; Ulid / Uuid are effective under distributed machines, so as a matter of fact, it is not a perfect guarantee.

**Comment by rcollina** [comment]
Hello,
Thank you for your reply.

I respect your decision. I'd just like to expand on the reasoning behind the initial question.

Let's pretend I have an Outbox table of messages. It is common to have one for each service in a distributed system. Each message gets an Id.

In all likelihood, such messages are created very quickly in memory and then stored into the Outbox table in a transaction. In other words, a batch of messages is created by the application's business logic and then stored.

I can ensure ordering is kept within a batch by using another column that keeps the index of each message, but this partially defeats the purpose of Ulids. Hence my question.

I don't need ordering guarantees across services and systems, I only need it locally.

The implementation would require a monotonic time source, and it would no doubt slow the generation of Ulids, which I guess is against the philosophy of this library.

Still, it would be nice to have a way to pass the timestamp component as ticks, either a constructor or a factory. Maybe it's already there and I've missed it.

Are you open to PRs in this regard?

Thank you.

**Comment by rcollina** [comment]
Hello @hadashiA,
I would appreciate some feedback, what are your thoughts on the scenario I outlined above?

Thank you
