### ISSUE TITLE
Campos tempid criado nas migrations

### ISSUE THREAD

**Issue by dionismda** [Cysharp/Ulid#44]
Estou implementando a lib e percebi esta sendo gerado um campo tempid nas migrations sendo este um campo unique alguem saberia me informar o porque da criação deste campo?

**Comment by hadashiA** [comment]
Sorry. I don't know what kind of trouble you are describing. The keyword "tempid" does not seem to belong to this repo.
If it is a bug in this library, please reopen it anytime with reproducible conditions.
