### ISSUE TITLE
Do you plan to create ToInt32 () or ToInt64 ()?

### ISSUE THREAD

**Issue by jacking75** [Cysharp/Ulid#5]
Hi
Ulid has the ability to convert to character and byte arrays. Are there any plans to convert them to integers?

**Comment by neuecc** [comment]
Ulid is [6byte timestamp, 10byte randomness].
It can convert to string(ToString) and byte[](ToByteArray, TryWriteBytes) but can not to Int32 or Int64.

If retrieve timestamp, you can use `.Time` as `DateTimeOffset` and it can convert to Int64(`Ticks`, `ToUnixTimeMilliseconds`, `ToUnixTimeSeconds`).

**Comment by jacking75** [comment]
thank you
