### ISSUE TITLE
Entity Framework Core more detailed usage guide

### ISSUE THREAD

**Issue by md-redwan-hossain** [Cysharp/Ulid#50]
The doc provides two classes `UlidToBytesConverter` and `UlidToStringConverter`. But which one to use when? For the class `BaseModel`, I am using the `UlidToStringConverter` for storing the ULID as string in the DB. But when to use the `UlidToBytesConverter`? Can you give any example? Also, is my approach of saving ULID as string in the DB any good?

```
public abstract class BaseModel
{
    public Ulid Id { get; set; }
    public DateTime CreatedAt { get; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}

```

```
public class BaseModelConfig : IEntityTypeConfiguration<BaseModel>
{
    public void Configure(EntityTypeBuilder<BaseModel> builder)
    {
        builder.Property(e => e.Id).HasConversion(new UlidToStringConverter());

        builder.UseTpcMappingStrategy();
        builder.Property(x => x.CreatedAt);

    }
}
```

**Comment by neuecc** [comment]
If you are considering performance, it is better to store Ulid in binary or Guid (if your DB supports Guid, I recommend Guid).
If performance is not that important, String is an easy choice to read.
In any case, do as you please with your preference.

**Comment by md-redwan-hossain** [comment]
> If you are considering performance, it is better to store Ulid in binary or Guid (if your DB supports Guid, I recommend Guid). If performance is not that important, String is an easy choice to read. In any case, do as you please with your preference.

I am using Postgresql Database and off course I seek performance, this is the core reason I am choosing ULID over GUID since ULID is sortable. However, I am not sure about your suggestion. Are you suggesting to store ULID as GUID? Also, if I store ULID as binary array, it becomes unreadable from the database without parsing. I

**Comment by neuecc** [comment]
Even if stored as Guid, the binary sequence inside is Ulid, so the characteristics should be preserved.
And, unlike storing as binary, it will be easier to handle.

**Comment by codymullins** [comment]
@neuecc I'm trying to understand this a bit better. Do we want to use the string converter but map to Guid or byte[] converter and map to Guid?

I'm able to use the string converter by itself and store it as text in PG, but I'm struggling to understand how it could be stored as the guid.

**Comment by md-redwan-hossain** [comment]
@codymullins You don't have to do any kind of mapping. Use regular `UUID` type in postgres. In C# code, use `Guid` type, and to store Ulid in that Guid, just use `Ulid.NewUlid().ToGuid()`

**Comment by gpproton** [comment]
I had the same issues using it with Entity Framework with the requirement of keeping my existing `Guid` types.
Here's my own solution below:

`UUIDv7Generator.cs`
```csharp
public class UUIDv7Generator : ValueGenerator {  
    protected override object NextValue(EntityEntry entry) => Ulid.NewUlid().ToGuid();  
    public override bool GeneratesTemporaryValues { get; }  
}
```

`SampleDbContext.cs`
```csharp
public class SampleDbContext : DbContext {
	protected override void OnModelCreating(ModelBuilder modelBuilder) {
	var entityTypes = modelBuilder.Model.GetEntityTypes()  
	    .Where(e => e.GetProperties().Any(p => p.ClrType == typeof(Guid))).ToList(); 

	  foreach (var entityType in entityTypes) {  
	      foreach (var property in entityType.GetProperties()) {
			        modelBuilder.Entity(entityType.ClrType)  
			                .Property(property.Name)  
			                .HasValueGenerator<UUIDv7Generator>();   
	      }  
	  }
	}
}
```
