### ISSUE TITLE
Simplify creating a new Ulid based on given DateTimeOffset

### ISSUE THREAD

**Issue by itsmuntadhar** [Cysharp/Ulid#59]
This addition would be great for readability since instead of `var idGte = Ulid.NewUlid(createdAtGte, new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 })` we can do `var idGte = Ulid.MinAt(createdAtGte)`

implemented in #58

**Comment by neuecc** [comment]
commented and closed at #58
