### ISSUE TITLE
Cannot install ulid-cli

### ISSUE THREAD

**Issue by alex13lopez** [Cysharp/Ulid#64]
Hi, probably noob issue here but posting because I don't know how to proceed... Thing is I'm trying to install the ulid-cli as indicated in the readme.md with `dotnet tool install --global ulid-cli` but it fails throwing an HttpRequestException: 401 Unauthorized:

![image](https://github.com/Cysharp/Ulid/assets/72864689/6a0214a2-4e60-488a-9a47-e37a327200a3)

What am I doing wrong? Thanks!

**Comment by hadashiA** [comment]
Hmm. The same command completed successfully in my hand.

Maybe you could try the following?
- Clear HTTP cache
    - ```bash
       dotnet nuget locals http-cache --clear
       ```
- ignore-failed-sources 
   - ```bash
      dotnet tool install -g ulid-cli --ignore-failed-sources
      ```

**Comment by alex13lopez** [comment]
![image](https://github.com/Cysharp/Ulid/assets/72864689/b77d036a-9b8c-4eff-b5a5-337a3bbaedd1)
Tried that and still the same issue : /
