### ISSUE TITLE
Parsing Guid Generated by Ulid.NewUlid().ToGuid() not working

### ISSUE THREAD

**Issue by lemawe** [Cysharp/Ulid#88]
I have a Guid 
var stampId = Ulid.NewUlid().ToGuid();

When I try to convert it back to guide with   Ulid.Parse(stampId .ToString()), it throws an exception :
Exception of type 'System.ArgumentException' was thrown.
For reference here is a valid Guid generated by the library that does not convert back to Ulid: 0193d4df-9cab-385a-9ba8-fcf5308c7e28

![image](https://github.com/user-attachments/assets/767e8452-3203-45e2-a26b-30bb691adf76)

**Comment by neuecc** [comment]
The String representation differs between Guid and Ulid.
The String can only be parsed in each of them.

**Comment by lemawe** [comment]
I don't understand it correctly. 
I have a Guid that has been generated as an Ulid and then converted to a Guid.
I want to parse the Guid back to an Ulid. I use Ulid.Parse(GeneratedGuid.ToString()).
Isn't it supposed to work?

**Comment by neuecc** [comment]
If you have converted it to a Guid string, you can only parse it as a Guid.
If you want to convert it back to a Ulid, you will need to parse it as a Guid first and then convert it to a Ulid.
In other words, `new Ulid(Guid.Parse(GuidString))`

**Comment by lemawe** [comment]
Ok I understand. Thanks for the clarification
